name = "UOPG0"
version = "0.1.0"
defaultTargets = ["UOPG0", "uopg0", "uopg1", "uopg2", "rankone"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.1"

[[lean_lib]]
name = "UOPG0"

[[lean_exe]]
name = "uopg0"
root = "Main"

[[lean_exe]]
name = "uopg1"
root = "Main1"

[[lean_exe]]
name = "uopg2"
root = "Main2"

[[lean_exe]]
name = "rankone"
root = "MainRank"
